<?php

/**
 * @file
 * Contains skyislife_slider.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_help().
 */
function skyislife_slider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the skyislife_slider module.
    case 'help.page.skyislife_slider':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function skyislife_slider_theme() {
  return [
    'skyislife_slider' => [
      'render element' => 'children',
    ],
    'skyislife' => [
      'variables' => [
        'items' => [],
        'attributes' => new Attribute(),
      ],
      'template' => 'skyislife',
      'file' => 'skyislife_slider.skyislife.inc'
    ],
  ];
}
